/**
 * Anchor integration tests for paylix_subscription_manager.
 * Run alongside payment_vault.ts under `anchor test`.
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import {
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  approve,
  getAccount,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { assert } from "chai";

describe("paylix_subscription_manager", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // @ts-expect-error — workspace name generated by anchor build
  const program = anchor.workspace.PaylixSubscriptionManager as anchor.Program;

  let owner: Keypair;
  let platform: Keypair;
  let merchant: Keypair;
  let buyer: Keypair;
  let mint: PublicKey;
  let buyerAta: PublicKey;
  let merchantAta: PublicKey;
  let platformAta: PublicKey;

  const [subConfig] = PublicKey.findProgramAddressSync(
    [Buffer.from("sub_config")],
    program.programId,
  );

  function subPda(id: bigint): PublicKey {
    const idBuf = Buffer.alloc(8);
    idBuf.writeBigUInt64LE(id);
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("sub"), idBuf],
      program.programId,
    );
    return pda;
  }

  before(async () => {
    owner = (provider.wallet as anchor.Wallet).payer;
    platform = Keypair.generate();
    merchant = Keypair.generate();
    buyer = Keypair.generate();

    const sig = await provider.connection.requestAirdrop(buyer.publicKey, 2_000_000_000);
    await provider.connection.confirmTransaction(sig, "confirmed");

    mint = await createMint(provider.connection, owner, owner.publicKey, null, 6);
    buyerAta = await createAssociatedTokenAccount(provider.connection, owner, mint, buyer.publicKey);
    merchantAta = await createAssociatedTokenAccount(provider.connection, owner, mint, merchant.publicKey);
    platformAta = await createAssociatedTokenAccount(provider.connection, owner, mint, platform.publicKey);
    await mintTo(provider.connection, owner, mint, buyerAta, owner, 10_000_000_000);
  });

  it("initializes the subscription config", async () => {
    await program.methods
      .initialize(platform.publicKey, 50)
      .accounts({
        config: subConfig,
        payer: owner.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    const cfg = await program.account.subscriptionManagerConfig.fetch(subConfig);
    assert.strictEqual(cfg.platformFeeBps, 50);
    assert.strictEqual(cfg.nextId.toNumber(), 0);
  });

  it("creates a subscription and charges the first cycle", async () => {
    const amount = new anchor.BN(10_000_000);
    const interval = new anchor.BN(60); // 60 seconds for fast test cycle
    const productId = Buffer.alloc(32, 3);
    const customerId = Buffer.alloc(32, 4);
    const sub = subPda(0n);

    // Buyer approves the subscription PDA as a delegate for enough allowance.
    await approve(
      provider.connection,
      buyer,
      buyerAta,
      sub, // delegate
      buyer.publicKey,
      10_000_000_000,
    );

    await program.methods
      .createSubscription(amount, interval, Array.from(productId), Array.from(customerId))
      .accounts({
        config: subConfig,
        subscription: sub,
        mint,
        buyer: buyer.publicKey,
        buyerAta,
        merchantAta,
        platformAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([buyer])
      .rpc();

    const merchantAcc = await getAccount(provider.connection, merchantAta);
    const platformAcc = await getAccount(provider.connection, platformAta);
    assert.strictEqual(Number(merchantAcc.amount), 9_950_000);
    assert.strictEqual(Number(platformAcc.amount), 50_000);

    const s = await program.account.subscription.fetch(sub);
    assert.strictEqual(s.amount.toNumber(), 10_000_000);
  });

  it("reverts chargeSubscription when not due yet", async () => {
    const sub = subPda(0n);
    let threw = false;
    try {
      await program.methods
        .chargeSubscription()
        .accounts({
          config: subConfig,
          subscription: sub,
          mint,
          buyerAta,
          merchantAta,
          platformAta,
          tokenProgram: TOKEN_PROGRAM_ID,
          caller: provider.wallet.publicKey,
        })
        .rpc();
    } catch (err) {
      threw = /NotDue|Not due/.test(String(err));
    }
    assert.strictEqual(threw, true);
  });

  it("cancel marks the subscription as cancelled", async () => {
    const sub = subPda(0n);
    await program.methods
      .cancelSubscription()
      .accounts({ subscription: sub, authority: buyer.publicKey })
      .signers([buyer])
      .rpc();
    const s = await program.account.subscription.fetch(sub);
    assert.strictEqual(s.status, 2); // Cancelled
  });
});
